-- =========================================================
-- Library Management System - Database Schema (SQLite)
-- =========================================================
-- You normally do NOT need to run this file by hand: the app
-- creates this exact schema (and this exact sample data)
-- automatically the first time it starts, in database/library.db.
-- This file is kept for reference, and as a way to reset your
-- data -- delete database/library.db and restart the app, or
-- run this file yourself against a fresh library.db with the
-- sqlite3 CLI:
--   sqlite3 database/library.db < database/library_db.sql
-- =========================================================

CREATE TABLE users (
    user_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    full_name      VARCHAR(100) NOT NULL,
    username       VARCHAR(50) UNIQUE NOT NULL,
    email          VARCHAR(100) UNIQUE NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE members (
    member_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(100) UNIQUE NOT NULL,
    phone         VARCHAR(15),
    address       VARCHAR(255),
    join_date     DATE NOT NULL DEFAULT CURRENT_DATE,
    status        VARCHAR(10) NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended'))
);

CREATE TABLE books (
    book_id           INTEGER PRIMARY KEY AUTOINCREMENT,
    title             VARCHAR(200) NOT NULL,
    author            VARCHAR(150) NOT NULL,
    isbn              VARCHAR(20) UNIQUE,
    category          VARCHAR(50),
    total_copies      INTEGER NOT NULL DEFAULT 1,
    available_copies  INTEGER NOT NULL DEFAULT 1,
    CHECK (available_copies >= 0 AND available_copies <= total_copies)
);

CREATE TABLE transactions (
    transaction_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    book_id          INTEGER NOT NULL,
    member_id        INTEGER NOT NULL,
    issue_date       DATE NOT NULL,
    due_date         DATE NOT NULL,
    return_date      DATE DEFAULT NULL,
    fine_amount      DECIMAL(8,2) DEFAULT 0.00,
    status           VARCHAR(10) NOT NULL DEFAULT 'ISSUED' CHECK (status IN ('ISSUED','RETURNED')),
    FOREIGN KEY (book_id) REFERENCES books(book_id),
    FOREIGN KEY (member_id) REFERENCES members(member_id)
);

CREATE INDEX idx_trans_status ON transactions(status);
CREATE INDEX idx_trans_member ON transactions(member_id);
CREATE INDEX idx_books_title  ON books(title);

-- Demo login: username "admin", password "admin123"
-- (hash generated by PasswordUtil -- salted SHA-256, format salt:hash)
INSERT INTO users (full_name, username, email, password_hash) VALUES
('Demo Admin', 'admin', 'admin@stacks.local',
 '53d85f80c747b20eba9508f8be0ca600:417a46d0ffed873b4b543d0678d74bac797936f8f19820d4ec0a7ad6e28b4488');

INSERT INTO members (name, email, phone, address) VALUES
('Aditi Sharma', 'aditi.sharma@example.com', '9876543210', 'Mumbai, MH'),
('Rohan Verma',  'rohan.verma@example.com',  '9123456780', 'Pune, MH'),
('Neha Kulkarni','neha.kulkarni@example.com','9988776655', 'Nagpur, MH');

INSERT INTO books (title, author, isbn, category, total_copies, available_copies) VALUES
('Clean Code', 'Robert C. Martin', '9780132350884', 'Programming', 3, 3),
('The Pragmatic Programmer', 'David Thomas', '9780201616224', 'Programming', 2, 2),
('Introduction to Algorithms', 'Thomas H. Cormen', '9780262033848', 'Computer Science', 2, 2),
('Wings of Fire', 'A.P.J. Abdul Kalam', '9788173711466', 'Biography', 4, 4),
('Sapiens', 'Yuval Noah Harari', '9780062316097', 'History', 3, 3);
